# Generated by Django 4.0 on 2022-01-05 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_receitas', '0002_receita_pessoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='publicar',
            field=models.BooleanField(default=False),
        ),
    ]
