# Generated by Django 4.0 on 2022-01-05 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_receitas', '0003_receita_publicar'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='./fotos/%d/%m/%Y/'),
        ),
    ]
