version: "3.5"
services:
  db:
    image: postgres:10.1-alpine
    ports:
      - "5432:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - .:/api
    ports:
      - "${DJANGO_BIND_PORT}:${DJANGO_BIND_PORT}"
    depends_on:
      - db
    command: [
      "./wait-for-it.sh",
      "db:5432",
      "--",
      "sh",
      "./scripts_sh/start.sh"
    ]